# Generated by Django 4.2.3 on 2023-07-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarnotTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_fk_id", models.IntegerField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("time_stamp", models.DateTimeField()),
                ("sts", models.DateTimeField()),
                ("speed", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
